export type EmployeeColumn = {
  key: string;
  title: string;
  show: boolean;
  orderable: boolean;
  exportable: boolean;
  hide: boolean;
};

export const EMPLOYEE_TABLE_COLUMNS = [
  { key: "id", title: "ID", show: true, orderable: true, exportable: true, hide: false },
  { key: "login", title: "Username", show: true, orderable: true, exportable: false, hide: false },
  { key: "fname", title: "Worker name", show: true, orderable: true, exportable: true, hide: false },
  { key: "customers_count", title: "Customers count", show: true, orderable: true, exportable: false, hide: false },
  { key: "finance_customers_count", title: "Finance count", show: true, orderable: true, exportable: false, hide: false },
  { key: "acl_permissions", title: "Custom Permissions", show: true, orderable: false, exportable: false, hide: false },
  { key: "phone_ext_desk", title: "Desk Voip", show: true, orderable: false, exportable: false, hide: false },
  { key: "phone_ext", title: "Ext", show: true, orderable: false, exportable: false, hide: false },
  { key: "email", title: "Email", show: true, orderable: true, exportable: false, hide: false },
  { key: "language", title: "Language", show: true, orderable: true, exportable: false, hide: false },
  { key: "google2fa_enable", title: "Google 2FA Enabled", show: true, orderable: true, exportable: false, hide: false },
  { key: "additional_security_enable", title: "Additional Security Enabled", show: true, orderable: true, exportable: true, hide: false },
  { key: "group", title: "Department", show: true, orderable: true, exportable: false, hide: false },
  { key: "active", title: "Active", show: true, orderable: true, exportable: true, hide: false },
  { key: "password_revoked", title: "Password Revoked", show: true, orderable: true, exportable: false, hide: false },
  { key: "created_at", title: "Created", show: true, orderable: true, exportable: false, hide: false },
  { key: "last_login", title: "Last Login", show: true, orderable: true, exportable: true, hide: false },
  { key: "actions", title: "Action", show: true, orderable: false, exportable: false, hide: false },
  { key: "OdriCall", title: "SIP - OdriCall", show: false, orderable: true, exportable: true, hide: true },
  { key: "Phonet", title: "SIP - Phonet", show: false, orderable: true, exportable: true, hide: true },
  { key: "MoMVOIP", title: "SIP - MoMVOIP", show: false, orderable: true, exportable: true, hide: true },
  { key: "PhoneAsterisk", title: "SIP - PhoneAsterisk", show: false, orderable: true, exportable: true, hide: true },
  { key: "Siprom", title: "SIP - Siprom", show: false, orderable: true, exportable: true, hide: true },
  { key: "CommPeak", title: "SIP - CommPeak", show: false, orderable: true, exportable: true, hide: true },
  { key: "VoiceSpin", title: "SIP - VoiceSpin", show: false, orderable: true, exportable: true, hide: true },
  { key: "Voiso", title: "SIP - Voiso", show: false, orderable: true, exportable: true, hide: true },
  { key: "Binotel", title: "SIP - Binotel", show: false, orderable: true, exportable: true, hide: true },
  { key: "GlobalSim", title: "SIP - GlobalSim", show: false, orderable: true, exportable: true, hide: true },
  { key: "PBX", title: "SIP - PBX", show: false, orderable: true, exportable: true, hide: true },
  { key: "Asterisk", title: "SIP - Asterisk", show: false, orderable: true, exportable: true, hide: true },
  { key: "Arcom", title: "SIP - Arcom", show: false, orderable: true, exportable: true, hide: true },
  { key: "Asystem", title: "SIP - Asystem", show: false, orderable: true, exportable: true, hide: true },
  { key: "SipNet", title: "SIP - SipNet", show: false, orderable: true, exportable: true, hide: true },
  { key: "VoipPlus", title: "SIP - VoipPlus", show: false, orderable: true, exportable: true, hide: true },
  { key: "Zadarma", title: "SIP - Zadarma", show: false, orderable: true, exportable: true, hide: true },
  { key: "Coperato", title: "SIP - Coperato", show: false, orderable: true, exportable: true, hide: true },
  { key: "SquareTalk", title: "SIP - SquareTalk", show: false, orderable: true, exportable: true, hide: true },
  { key: "Prime", title: "SIP - Prime", show: false, orderable: true, exportable: true, hide: true },
  { key: "TelTel", title: "SIP - TelTel", show: false, orderable: true, exportable: true, hide: true },
  { key: "Fusion", title: "SIP - Fusion", show: false, orderable: true, exportable: true, hide: true },
  { key: "PortaOne", title: "SIP - PortaOne", show: false, orderable: true, exportable: true, hide: true },
  { key: "SquareTalkWeb", title: "SIP - SquareTalkWeb", show: false, orderable: true, exportable: true, hide: true },
  { key: "CoperatoExt", title: "SIP - CoperatoExt", show: false, orderable: true, exportable: true, hide: true },
  { key: "SmartSwitch", title: "SIP - SmartSwitch", show: false, orderable: true, exportable: true, hide: true },
  { key: "Sancom", title: "SIP - Sancom", show: false, orderable: true, exportable: true, hide: true },
  { key: "EnSwitch", title: "SIP - EnSwitch", show: false, orderable: true, exportable: true, hide: true },
  { key: "UniTalk", title: "SIP - UniTalk", show: false, orderable: true, exportable: true, hide: true },
  { key: "AsteriskAri", title: "SIP - AsteriskAri", show: false, orderable: true, exportable: true, hide: true },
  { key: "Voiceflow", title: "SIP - Voiceflow", show: false, orderable: true, exportable: true, hide: true },
  { key: "GlobalCall", title: "SIP - GlobalCall", show: false, orderable: true, exportable: true, hide: true },
  { key: "Voip365", title: "SIP - Voip365", show: false, orderable: true, exportable: true, hide: true },
  { key: "Widecom", title: "SIP - Widecom", show: false, orderable: true, exportable: true, hide: true },
  { key: "Octella", title: "SIP - Octella", show: false, orderable: true, exportable: true, hide: true },
  { key: "PrimeCall", title: "SIP - PrimeCall", show: false, orderable: true, exportable: true, hide: true },
  { key: "GTel", title: "SIP - GTel", show: false, orderable: true, exportable: true, hide: true },
  { key: "Trast365", title: "SIP - Trast365", show: false, orderable: true, exportable: true, hide: true },
  { key: "DidPbx1", title: "SIP - DidPbx1", show: false, orderable: true, exportable: true, hide: true },
  { key: "LikeTelecom", title: "SIP - LikeTelecom", show: false, orderable: true, exportable: true, hide: true },
  { key: "Voicex", title: "SIP - Voicex", show: false, orderable: true, exportable: true, hide: true },
  { key: "Widecomc2c", title: "SIP - Widecomc2c", show: false, orderable: true, exportable: true, hide: true },
  { key: "CrocoCalls", title: "SIP - CrocoCalls", show: false, orderable: true, exportable: true, hide: true },
  { key: "Noriztel", title: "SIP - Noriztel", show: false, orderable: true, exportable: true, hide: true },
  { key: "AsteriskAriV2", title: "SIP - AsteriskAriV2", show: false, orderable: true, exportable: true, hide: true },
  { key: "MMDCCC", title: "SIP - MMDCCC", show: false, orderable: true, exportable: true, hide: true },
  { key: "GlobalTel", title: "SIP - GlobalTel", show: false, orderable: true, exportable: true, hide: true },
  { key: "ATC", title: "SIP - ATC", show: false, orderable: true, exportable: true, hide: true },
  { key: "Voxonics", title: "SIP - Voxonics", show: false, orderable: true, exportable: true, hide: true },
  { key: "Tikal", title: "SIP - Tikal", show: false, orderable: true, exportable: true, hide: true },
  { key: "Profitelecom", title: "SIP - Profitelecom", show: false, orderable: true, exportable: true, hide: true },
  { key: "DeepCall", title: "SIP - DeepCall", show: false, orderable: true, exportable: true, hide: true },
  { key: "Iqvoip", title: "SIP - Iqvoip", show: false, orderable: true, exportable: true, hide: true },
  { key: "JustCall", title: "SIP - JustCall", show: false, orderable: true, exportable: true, hide: true },
] satisfies EmployeeColumn[];

export const EMPLOYEE_SIP_PROVIDER_KEYS = EMPLOYEE_TABLE_COLUMNS.filter(
  (column) => column.hide,
).map((column) => column.key);
